---
title: "Research"
---

## Current Research

### Genetic Contributors to Alzheimer's Disease

**NIH/NIA Diversity Supplement to Protective Genetic Variants for Alzheimer Disease in the Amish**\
*Role: Post-baccalaureate Trainee*\
*August 2024 - May 2027*

The proposed research focuses on identifying genetic contributors to Alzheimer disease (AD) risk and protection, with a particular emphasis on founder (Amish) and diverse (African American) populations. The specific aim for this diversity supplement is to construct and describe genetic risk score distributions for two clinically recognized depressions: post-partum depression (PPD) and major depressive disorder (MDD).

### Previous Research Experience

#### Case Western Reserve University School of Medicine

*Research Technician I & PREP Scholar*\
*July 2023 - Present*

-   Focus on genetics and postpartum depression in African American women
-   Presented research at multiple conferences including ABRCMS and ASHG Annual Meeting

#### University of California San Diego

*Lab Assistant & Bridges to Stem Cell Research Intern*\
*August 2021 - June 2023*

-   Worked on optimizing derivation of decidual-type natural killer cells from human pluripotent stem cells
-   Presented research at International Society for Stem Cell Research Annual Meeting
