---
title: "Presentations & Publications"
---

## Recent Presentations

### Oral Presentations

1.  **Genetics of postpartum depression in African American women**\
    Case Western Reserve University School of Medicine Graduate and Medical Student Research Day\
    Cleveland, Ohio, October 22, 2024

2.  **Characterizing the genetic components of postpartum depression in African Americans**\
    Case Western Reserve University Postbaccalaureate Research Education Program Research Day\
    Cleveland, Ohio, May 16, 2024

3.  **Chloroquine-induced lysosomal dysfunction causes a shift in microglia phenotype**\
    UCSD Medical Scientist Training Program Summer Undergraduate Research Fellowship Research Symposium\
    San Diego, California, August 12, 2021

### Poster Presentations

1.  **Genetics of postpartum depression in African American women**\
    Annual Biomedical Research Conference for Minoritized Scientists (ABRCMS)\
    Pittsburgh, Pennsylvania, November 13-16, 2024

2.  **Genetics of postpartum depression in African American women**\
    American Society of Human Genetics (ASHG) Annual Meeting\
    Denver, Colorado, November 5-9, 2024

[View full list of presentations in CV](../files/CV.pdf)
